name: main.yml (CI Workflow)

# Déclenche l'action à chaque push sur la branche main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code
      uses: actions/checkout@v4

    - name: Installation de Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest black pylint radon

    - name: Vérification du formatage (Black)
      # L'option --check fait échouer le test si le code n'est pas bien formaté
      run: |
        black --check src/ tests/

    - name: Analyse statique (Pylint)
      run: |
        pylint src/

    - name: Analyse de complexité (Radon)
      run: |
        radon cc src/ -a
        radon mi src/

    - name: Lancement des tests (Pytest)
      run: |
        pytest tests/


###############################################

deploy-testpypi:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }} # Utilise secrets ici
        run: |
          pip install twine
          twine upload --repository testpypi dist/*

deploy-pypi:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install twine
          twine upload dist/*